apiVersion: modus.dev/v1
kind: Agent
metadata:
  externalUid: c3baf2fb-3d0b-4a0e-94cc-7fdccd0deaef
  name: New test for temas
spec:
  type: task
  description: ""
  trigger:
    type: manual
  agentSelection:
    agents:
      - skill: test-skill
        priorityOrder: 1
    model: claude-sonnet-4.6
  workflowStructure:
    nodes: []
    edges: []
  access:
    groupPermissions:
      __everyone__:
        use: true
        manage: true
    guardrails: []
    ownerUserId: user_394iVT1ubV3OXrGmIqI0a8QrXLP
    ownerEmail: eladdo@modus.direct
  interfaces: []
